/*
 * generated by Xtext 2.34.0
 */
package org.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.MCCRuntimeModule;
import org.xtext.MCCStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MCCIdeSetup extends MCCStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MCCRuntimeModule(), new MCCIdeModule()));
	}
	
}
