/*
 * generated by Xtext 2.34.0
 */
package org.xtext.generator

import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.AbstractGenerator
import org.eclipse.xtext.generator.IFileSystemAccess2
import org.eclipse.xtext.generator.IGeneratorContext
import org.xtext.mCC.Model
import java.util.ArrayList
import java.util.Hashtable
import org.xtext.mCC.Application
import org.xtext.mCC.Fragment
import org.xtext.mCC.Structure
import org.xtext.mCC.Cloud
import java.io.BufferedReader
import java.io.InputStreamReader


class CommonResult {
	public ArrayList<String> locations
	public ArrayList<String[]> transitions
	public String initLocationSpecial
	public String initLocation
	
	new(ArrayList<String> locations, ArrayList<String[]> transitions, String initLocationSpecial, String initLocation) {
		this.locations = locations
		this.transitions = transitions
		this.initLocationSpecial = initLocationSpecial
		this.initLocation = initLocation
	}
}

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class MCCGenerator extends AbstractGenerator {
	var int id=0;
	var registry=new Hashtable<String, Integer>();

	override void doGenerate(Resource resource, IFileSystemAccess2 fsa, IGeneratorContext context) {
		id=0
		for(m:resource.allContents.toIterable.filter(typeof(Model))){
			// Generate UPPAAL files for all applications
			for(a:m.applications){
				id=0  // Reset ID counter for each application
				fsa.generateFile(a.name+".xml", a.compile(resource))
			}
			// Also generate system-level files if needed
			for(s:m.systems){
				fsa.generateFile(s.name+"_system.xml", s.devices.get(0).applications.get(0).compile(resource))
			}
		}
	}
	
	def compile(Application a, Resource r){
		var i=0;
		for(fragment:a.fragments){
			registry.put(fragment.name, i)
			i=i+1
		}
		
		'''<?xml version="1.0" encoding="utf-8"?><!DOCTYPE nta PUBLIC '-//Uppaal Team//DTD Flat System 1.1//EN' 'http://www.it.uu.se/research/group/darts/uppaal/flat-1_1.dtd'>
		<nta>
		<declaration>«a.GlobalDeclarations(r)»</declaration>
		«FOR fragment:a.fragments»
		«fragment.compile(a.structure)»
		«ENDFOR»
		
		«CloudExecutor»
		«EnergyMonitor»
		
		<system>system «FOR f:a.fragments»«f.name»,«ENDFOR»CloudExecutor, EnergyMonitor;</system>
		</nta>'''
	}
	

	
	def compile(Fragment f, Structure s){ 
		val edges=s.edges.filter[start.name==f.name]
		val leafFragment = edges.length==0
		var middle=""
		val locations = new ArrayList<String>()
		val transitions = new ArrayList<String[]>()
		
		// Only create middle location for fragments that have outgoing edges
		if(leafFragment==false){
			middle="id"+ID
			locations.add(createLocation(middle, null))
		}
		
		// Create startLocation for fragments with outgoing edges
		// Will be used as final location in signal chains
		var startLocation = ""
		if(leafFragment==false) {
			startLocation = "id"+ID
			locations.add(createLocation(startLocation, null))
		}
		
		for(e:edges){
			if(e.operator.toString=="-->"){
				for(destinationFragment:e.stop){
					// Non-deterministic choice: trigger one of the destination fragments
					// Non-deterministic choice: trigger one of the destination fragments
					transitions.add(#[middle.toString, startLocation, null, null, "execute["+registry.get(destinationFragment.name)+"]!",null])
				}
			}
			
			if(e.operator.toString=="--|"){
				// Send all parallel signals from middle location, then go to startLocation
				val destinationList = e.stop.toList
				var String currentLoc = middle.toString
				
				for(i : 0..<destinationList.size){
					val destinationFragment = destinationList.get(i)
					if(i == destinationList.size - 1){
						// Last signal - go to startLocation
						transitions.add(#[currentLoc, startLocation, null, null, "parallel["+registry.get(destinationFragment.name)+"]!",null])
					} else {
						// Create intermediate location for next signal
						val nextLoc = "id"+ID
						locations.add(createLocation(nextLoc, null))
						transitions.add(#[currentLoc, nextLoc, null, null, "parallel["+registry.get(destinationFragment.name)+"]!",null])
						currentLoc = nextLoc
					}
				}
			}
			
			if(e.operator.toString=="--::"){
				// Sequential execution: trigger fragments one by one
				val destinationFragments = e.stop.toList
				var String currentLoc = middle.toString
				
				for(i : 0..<destinationFragments.size){
					val destinationFragment = destinationFragments.get(i)
					if(i == destinationFragments.size - 1){
						// Last fragment - go to startLocation (or middle if no startLocation)
						transitions.add(#[currentLoc, startLocation, null, null, "execute["+registry.get(destinationFragment.name)+"]!",null])
					} else {
						// Create intermediate location for next fragment
						val nextLoc = "id"+ID
						locations.add(createLocation(nextLoc, null))
						transitions.add(#[currentLoc, nextLoc, null, null, "execute["+registry.get(destinationFragment.name)+"]!",null])
						currentLoc = nextLoc
					}
				}
			}
		}
		
		val commonResult = commonPart("", middle, registry.get(f.name).toString, s, f, leafFragment, "")
		locations.addAll(commonResult.locations)
		transitions.addAll(commonResult.transitions)
		
		// For non-leaf fragments, ensure startLocation connects back to waiting state
		if(leafFragment==false && startLocation != ""){
			val targetLocation = if(commonResult.initLocationSpecial != null) commonResult.initLocationSpecial else commonResult.initLocation
			// After triggering all parallel signals, return to waiting
			transitions.add(#[startLocation, targetLocation, null, null, null, null])
		}
		

		
		'''
		<template>
		<name x="5" y="5"> «f.name» </name>
		<declaration></declaration>
		
		«FOR location:locations»
		«location»
		«ENDFOR»
		
		«IF commonResult.initLocationSpecial!=null»
		<init ref="«commonResult.initLocationSpecial»"/>
		«ELSE»
		<init ref="«commonResult.initLocation»"/>
		«ENDIF»
		
		«FOR transition:transitions»
		«createTransition(transition.get(0),transition.get(1), transition.get(2), transition.get(3), transition.get(4), transition.get(5))»
		«ENDFOR»
		</template>
		'''
	}
	
	
	def CommonResult commonPart(String initLocation, String terminalID, String fragmentID, Structure s, Fragment f, Boolean leafFragment, String startLocation){
		val String waitingLocation="id"+ID
		val String executingLocation="id"+ID
		val locations = new ArrayList<String>()
		val transitions = new ArrayList<String[]>()
		
		locations.add(createLocation(waitingLocation, null))  
		locations.add(createLocation(executingLocation, "committed"))
		
		// Fragment execution flow: waiting -> executing -> (done or trigger successors)
		if(leafFragment==false){
			// Non-leaf: executing -> terminalID (to trigger successors)
			transitions.add(#[executingLocation, terminalID, null, null, "completed["+fragmentID+"]!", "prepareExecution("+ fragmentID+")"])
		}else{
			// Leaf: executing -> waitingLocation (loop back to waiting)
			transitions.add(#[executingLocation, waitingLocation, null, null, "completed["+fragmentID+"]!", "prepareExecution("+ fragmentID+")"])
		}

		var String initLocationSpecial=null;
		if(f.init=='init'){
			initLocationSpecial="id"+ID
			locations.add(createLocation(initLocationSpecial, null))
			// Init fragments start immediately
			transitions.add(#[initLocationSpecial, executingLocation, null, null, null, null])
			// Use initLocationSpecial as the main waiting location for init fragments
			var String actualWaitingLocation = initLocationSpecial
			
			// Handle parallel execution triggers for init fragments (avoid duplicates)
			val parallelEdges = s.edges.filter[operator.toString=="--|" && stop.contains(f)]
			if(parallelEdges.empty==false){
				transitions.add(#[actualWaitingLocation, executingLocation, null, null, "parallel["+fragmentID+"]?", null])
			}
			
			return new CommonResult(locations, transitions, initLocationSpecial, actualWaitingLocation)
		}else{
			// Regular fragments wait for execute signal
			transitions.add(#[waitingLocation, executingLocation, null, null, "execute["+fragmentID+"]?", null])
			
			// Handle parallel execution triggers for regular fragments (avoid duplicates)
			val parallelEdges = s.edges.filter[operator.toString=="--|" && stop.contains(f)]
			if(parallelEdges.empty==false){
				transitions.add(#[waitingLocation, executingLocation, null, null, "parallel["+fragmentID+"]?", null])
			}
			
			// For leaf fragments, ensure waitingLocation is returned to the waiting state after execution
			if(leafFragment){
				// Already handled above: executing -> waitingLocation
			}
			
			return new CommonResult(locations, transitions, null, waitingLocation)
		}
	}
	

	
	def int getID(){
		return id=id+1
	}
	def String getLastID(){
		return "id"+id
	}
	
	def String createLocation(String i, String type){
		'''
		<location id="«i»">
			<name>«i»</name>
			«IF type!=null»
			<«type»/>
			«ENDIF»
		</location>'''
	}
	
	def String createTransition(String s, String t, String select, String guard, String sync, String ass){
		'''
		<transition>
			<source ref="«s»"/>
			<target ref="«t»"/>
			«IF select!=null»	<label kind="select" >«select»</label>«ENDIF»
			«IF guard!=null»	<label kind="guard" >«guard»</label>«ENDIF»
			«IF sync!=null»	<label kind="synchronisation" >«sync»</label>«ENDIF»
			«IF ass!=null»	<label kind="assignment" >«ass»</label>«ENDIF»
		</transition>
		'''
	}
	
	def String CloudExecutor(){
		'''
		<template>
		<name>CloudExecutor</name>
		<declaration>
		void executeFragment(int fragmentId) {
			// Calculate energy consumption based on fragment characteristics
			int computationEnergy = Info[fragmentId].instructions * cloudEnergyPerInstruction;
			int memoryEnergy = Info[fragmentId].memory * cloudEnergyPerMemoryUnit;
			int communicationEnergy = Info[fragmentId].communicationData * cloudEnergyPerDataUnit;
			
			// Update total energy consumption
			totalEnergyConsumed += computationEnergy + memoryEnergy + communicationEnergy;
			
			// Update execution time
			executionTime += ((Info[fragmentId].instructions * 10) / cloudInstructions);
			if(executionTime == 0) executionTime = 1; // Minimum execution time
			
			// Mark fragment as completed
			fragmentsCompleted[fragmentId] = true;
		}
		</declaration>
		
		«val idle="id"+ID»
		«val executing="id"+ID»
		
		«createLocation(idle, null)»
		«createLocation(executing, "committed")»
		
		<init ref="«idle»"/>
		
		«createTransition(idle, executing, "f : id_t", null, "completed[f]?", "currentFragment = f")»
		«createTransition(executing, idle, null, null, null, "executeFragment(currentFragment)")»
		</template>
		'''
	}
	
	def String EnergyMonitor(){
		'''
		<template>
		<name>EnergyMonitor</name>
		<declaration>
		// Energy monitoring functions
		bool allFragmentsCompleted() {
			int i;
			for(i = 0; i &lt; N; i++) {
				if(!fragmentsCompleted[i]) return false;
			}
			return true;
		}
		
		int calculateTotalEnergy() {
			return totalEnergyConsumed;
		}
		
		int calculateAverageEnergyPerFragment() {
			if(N > 0) return totalEnergyConsumed / N;
			return 0;
		}
		</declaration>
		
		«val monitoring="id"+ID»
		«val finished="id"+ID»
		
		«createLocation(monitoring, null)»
		«createLocation(finished, null)»
		
		<init ref="«monitoring»"/>
		
		«createTransition(monitoring, finished, null, "allFragmentsCompleted()", null, "finalEnergyConsumption = calculateTotalEnergy()")»
		</template>
		'''
	}
	
	def String GlobalDeclarations(Application a, Resource r) {
		val cloud=r.allContents.toIterable.filter(typeof(Cloud)).last
		'''
		// Cloud-only energy consumption model
		const int N=«a.fragments.size»;
		typedef int[0, N-1] id_t;
		
		// Cloud computing parameters
		const int cloudInstructions=«cloud.cpuInstructions»;
		
		// Energy consumption parameters (units: millijoules)
		const int cloudEnergyPerInstruction = «cloud.energyPerInstruction»;    // mJ per instruction
		const int cloudEnergyPerMemoryUnit = «cloud.energyPerMemoryUnit»;     // mJ per memory unit
		const int cloudEnergyPerDataUnit = «cloud.energyPerDataUnit»;       // mJ per communication data unit
		
		// Communication channels
		chan execute[N], completed[N], parallel[N];
		
		// Energy tracking variables
		int totalEnergyConsumed = 0;
		int finalEnergyConsumption = 0;
		int executionTime = 0;
		
		// Fragment tracking
		int currentFragment;
		bool fragmentsCompleted[N];
		int fragmentsExecuted = 0;
		
		// Fragment information structure
		typedef struct {
			int instructions;           // Number of instructions to execute
			int memory;                // Memory requirements
			int communicationData;     // Data transfer requirements
		} FragmentInfo;
		
		const FragmentInfo Info[N] = {
			«FOR f:a.fragments»
			{«f.instructions», «f.memory», «f.communicationData»}
			«IF f.name!=a.fragments.last.name»,«ENDIF»
			«ENDFOR»
		};
		

		
		// Helper functions
		void prepareExecution(int fragmentId) {
			// Initialize fragment for execution
			fragmentsCompleted[fragmentId] = false;
		}
		'''
	}
}
