/**
 * generated by Xtext 2.34.0
 */
package org.xtext.mCC;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cloud</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mCC.Cloud#getCpuInstructions <em>Cpu Instructions</em>}</li>
 *   <li>{@link org.xtext.mCC.Cloud#getEnergyPerInstruction <em>Energy Per Instruction</em>}</li>
 *   <li>{@link org.xtext.mCC.Cloud#getEnergyPerMemoryUnit <em>Energy Per Memory Unit</em>}</li>
 *   <li>{@link org.xtext.mCC.Cloud#getEnergyPerDataUnit <em>Energy Per Data Unit</em>}</li>
 * </ul>
 *
 * @see org.xtext.mCC.MCCPackage#getCloud()
 * @model
 * @generated
 */
public interface Cloud extends Device
{
  /**
   * Returns the value of the '<em><b>Cpu Instructions</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cpu Instructions</em>' attribute.
   * @see #setCpuInstructions(int)
   * @see org.xtext.mCC.MCCPackage#getCloud_CpuInstructions()
   * @model
   * @generated
   */
  int getCpuInstructions();

  /**
   * Sets the value of the '{@link org.xtext.mCC.Cloud#getCpuInstructions <em>Cpu Instructions</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cpu Instructions</em>' attribute.
   * @see #getCpuInstructions()
   * @generated
   */
  void setCpuInstructions(int value);

  /**
   * Returns the value of the '<em><b>Energy Per Instruction</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Energy Per Instruction</em>' attribute.
   * @see #setEnergyPerInstruction(int)
   * @see org.xtext.mCC.MCCPackage#getCloud_EnergyPerInstruction()
   * @model
   * @generated
   */
  int getEnergyPerInstruction();

  /**
   * Sets the value of the '{@link org.xtext.mCC.Cloud#getEnergyPerInstruction <em>Energy Per Instruction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Energy Per Instruction</em>' attribute.
   * @see #getEnergyPerInstruction()
   * @generated
   */
  void setEnergyPerInstruction(int value);

  /**
   * Returns the value of the '<em><b>Energy Per Memory Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Energy Per Memory Unit</em>' attribute.
   * @see #setEnergyPerMemoryUnit(int)
   * @see org.xtext.mCC.MCCPackage#getCloud_EnergyPerMemoryUnit()
   * @model
   * @generated
   */
  int getEnergyPerMemoryUnit();

  /**
   * Sets the value of the '{@link org.xtext.mCC.Cloud#getEnergyPerMemoryUnit <em>Energy Per Memory Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Energy Per Memory Unit</em>' attribute.
   * @see #getEnergyPerMemoryUnit()
   * @generated
   */
  void setEnergyPerMemoryUnit(int value);

  /**
   * Returns the value of the '<em><b>Energy Per Data Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Energy Per Data Unit</em>' attribute.
   * @see #setEnergyPerDataUnit(int)
   * @see org.xtext.mCC.MCCPackage#getCloud_EnergyPerDataUnit()
   * @model
   * @generated
   */
  int getEnergyPerDataUnit();

  /**
   * Sets the value of the '{@link org.xtext.mCC.Cloud#getEnergyPerDataUnit <em>Energy Per Data Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Energy Per Data Unit</em>' attribute.
   * @see #getEnergyPerDataUnit()
   * @generated
   */
  void setEnergyPerDataUnit(int value);

} // Cloud
