/**
 * generated by Xtext 2.34.0
 */
package org.xtext.mCC;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dummy Device</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.mCC.MCCPackage#getDummyDevice()
 * @model
 * @generated
 */
public interface DummyDevice extends Device
{
} // DummyDevice
