/**
 * generated by Xtext 2.34.0
 */
package org.xtext.mCC;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Edge</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mCC.Edge#getStart <em>Start</em>}</li>
 *   <li>{@link org.xtext.mCC.Edge#getOperator <em>Operator</em>}</li>
 *   <li>{@link org.xtext.mCC.Edge#getStop <em>Stop</em>}</li>
 * </ul>
 *
 * @see org.xtext.mCC.MCCPackage#getEdge()
 * @model
 * @generated
 */
public interface Edge extends EObject
{
  /**
   * Returns the value of the '<em><b>Start</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start</em>' reference.
   * @see #setStart(Fragment)
   * @see org.xtext.mCC.MCCPackage#getEdge_Start()
   * @model
   * @generated
   */
  Fragment getStart();

  /**
   * Sets the value of the '{@link org.xtext.mCC.Edge#getStart <em>Start</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start</em>' reference.
   * @see #getStart()
   * @generated
   */
  void setStart(Fragment value);

  /**
   * Returns the value of the '<em><b>Operator</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.mCC.Operator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' attribute.
   * @see org.xtext.mCC.Operator
   * @see #setOperator(Operator)
   * @see org.xtext.mCC.MCCPackage#getEdge_Operator()
   * @model
   * @generated
   */
  Operator getOperator();

  /**
   * Sets the value of the '{@link org.xtext.mCC.Edge#getOperator <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' attribute.
   * @see org.xtext.mCC.Operator
   * @see #getOperator()
   * @generated
   */
  void setOperator(Operator value);

  /**
   * Returns the value of the '<em><b>Stop</b></em>' reference list.
   * The list contents are of type {@link org.xtext.mCC.Fragment}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stop</em>' reference list.
   * @see org.xtext.mCC.MCCPackage#getEdge_Stop()
   * @model
   * @generated
   */
  EList<Fragment> getStop();

} // Edge
