/**
 * generated by Xtext 2.34.0
 */
package org.xtext.mCC;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mCC.Model#getDevices <em>Devices</em>}</li>
 *   <li>{@link org.xtext.mCC.Model#getApplications <em>Applications</em>}</li>
 *   <li>{@link org.xtext.mCC.Model#getSystems <em>Systems</em>}</li>
 * </ul>
 *
 * @see org.xtext.mCC.MCCPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Devices</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.mCC.Device}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Devices</em>' containment reference list.
   * @see org.xtext.mCC.MCCPackage#getModel_Devices()
   * @model containment="true"
   * @generated
   */
  EList<Device> getDevices();

  /**
   * Returns the value of the '<em><b>Applications</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.mCC.Application}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Applications</em>' containment reference list.
   * @see org.xtext.mCC.MCCPackage#getModel_Applications()
   * @model containment="true"
   * @generated
   */
  EList<Application> getApplications();

  /**
   * Returns the value of the '<em><b>Systems</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.mCC.System}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Systems</em>' containment reference list.
   * @see org.xtext.mCC.MCCPackage#getModel_Systems()
   * @model containment="true"
   * @generated
   */
  EList<org.xtext.mCC.System> getSystems();

} // Model
