/**
 * generated by Xtext 2.34.0
 */
package org.xtext.mCC;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Structure</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mCC.Structure#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.mCC.Structure#getEdges <em>Edges</em>}</li>
 * </ul>
 *
 * @see org.xtext.mCC.MCCPackage#getStructure()
 * @model
 * @generated
 */
public interface Structure extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.mCC.MCCPackage#getStructure_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.mCC.Structure#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Edges</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.mCC.Edge}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Edges</em>' containment reference list.
   * @see org.xtext.mCC.MCCPackage#getStructure_Edges()
   * @model containment="true"
   * @generated
   */
  EList<Edge> getEdges();

} // Structure
