/**
 * generated by Xtext 2.34.0
 */
package org.xtext.generator;

import java.util.ArrayList;

@SuppressWarnings("all")
public class CommonResult {
  public ArrayList<String> locations;

  public ArrayList<String[]> transitions;

  public String initLocationSpecial;

  public String initLocation;

  public CommonResult(final ArrayList<String> locations, final ArrayList<String[]> transitions, final String initLocationSpecial, final String initLocation) {
    this.locations = locations;
    this.transitions = transitions;
    this.initLocationSpecial = initLocationSpecial;
    this.initLocation = initLocation;
  }
}
