/**
 * generated by Xtext 2.34.0
 */
package org.xtext.generator;

import com.google.common.base.Objects;
import com.google.common.collect.Iterables;
import java.util.ArrayList;
import java.util.Hashtable;
import java.util.List;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.Conversions;
import org.eclipse.xtext.xbase.lib.ExclusiveRange;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import org.xtext.mCC.Application;
import org.xtext.mCC.Cloud;
import org.xtext.mCC.Edge;
import org.xtext.mCC.Fragment;
import org.xtext.mCC.Model;
import org.xtext.mCC.Structure;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class MCCGenerator extends AbstractGenerator {
  private int id = 0;

  private Hashtable<String, Integer> registry = new Hashtable<String, Integer>();

  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    this.id = 0;
    Iterable<Model> _filter = Iterables.<Model>filter(IteratorExtensions.<EObject>toIterable(resource.getAllContents()), Model.class);
    for (final Model m : _filter) {
      {
        EList<Application> _applications = m.getApplications();
        for (final Application a : _applications) {
          {
            this.id = 0;
            String _name = a.getName();
            String _plus = (_name + ".xml");
            fsa.generateFile(_plus, this.compile(a, resource));
          }
        }
        EList<org.xtext.mCC.System> _systems = m.getSystems();
        for (final org.xtext.mCC.System s : _systems) {
          String _name = s.getName();
          String _plus = (_name + "_system.xml");
          fsa.generateFile(_plus, this.compile(s.getDevices().get(0).getApplications().get(0), resource));
        }
      }
    }
  }

  public CharSequence compile(final Application a, final Resource r) {
    CharSequence _xblockexpression = null;
    {
      int i = 0;
      EList<Fragment> _fragments = a.getFragments();
      for (final Fragment fragment : _fragments) {
        {
          this.registry.put(fragment.getName(), Integer.valueOf(i));
          i = (i + 1);
        }
      }
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("<?xml version=\"1.0\" encoding=\"utf-8\"?><!DOCTYPE nta PUBLIC \'-//Uppaal Team//DTD Flat System 1.1//EN\' \'http://www.it.uu.se/research/group/darts/uppaal/flat-1_1.dtd\'>");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("<nta>");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("<declaration>");
      String _GlobalDeclarations = this.GlobalDeclarations(a, r);
      _builder.append(_GlobalDeclarations, "\t\t");
      _builder.append("</declaration>");
      _builder.newLineIfNotEmpty();
      {
        EList<Fragment> _fragments_1 = a.getFragments();
        for(final Fragment fragment_1 : _fragments_1) {
          _builder.append("\t\t");
          CharSequence _compile = this.compile(fragment_1, a.getStructure());
          _builder.append(_compile, "\t\t");
          _builder.newLineIfNotEmpty();
        }
      }
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      String _CloudExecutor = this.CloudExecutor();
      _builder.append(_CloudExecutor, "\t\t");
      _builder.newLineIfNotEmpty();
      _builder.append("\t\t");
      String _EnergyMonitor = this.EnergyMonitor();
      _builder.append(_EnergyMonitor, "\t\t");
      _builder.newLineIfNotEmpty();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("<system>system ");
      {
        EList<Fragment> _fragments_2 = a.getFragments();
        for(final Fragment f : _fragments_2) {
          String _name = f.getName();
          _builder.append(_name, "\t\t");
          _builder.append(",");
        }
      }
      _builder.append("CloudExecutor, EnergyMonitor;</system>");
      _builder.newLineIfNotEmpty();
      _builder.append("\t\t");
      _builder.append("</nta>");
      _xblockexpression = _builder;
    }
    return _xblockexpression;
  }

  public CharSequence compile(final Fragment f, final Structure s) {
    CharSequence _xblockexpression = null;
    {
      final Function1<Edge, Boolean> _function = (Edge it) -> {
        String _name = it.getStart().getName();
        String _name_1 = f.getName();
        return Boolean.valueOf(Objects.equal(_name, _name_1));
      };
      final Iterable<Edge> edges = IterableExtensions.<Edge>filter(s.getEdges(), _function);
      int _length = ((Object[])Conversions.unwrapArray(edges, Object.class)).length;
      final boolean leafFragment = (_length == 0);
      String middle = "";
      final ArrayList<String> locations = new ArrayList<String>();
      final ArrayList<String[]> transitions = new ArrayList<String[]>();
      if ((leafFragment == false)) {
        int _iD = this.getID();
        String _plus = ("id" + Integer.valueOf(_iD));
        middle = _plus;
        locations.add(this.createLocation(middle, null));
      }
      String startLocation = "";
      if ((leafFragment == false)) {
        int _iD_1 = this.getID();
        String _plus_1 = ("id" + Integer.valueOf(_iD_1));
        startLocation = _plus_1;
        locations.add(this.createLocation(startLocation, null));
      }
      for (final Edge e : edges) {
        {
          String _string = e.getOperator().toString();
          boolean _equals = Objects.equal(_string, "-->");
          if (_equals) {
            EList<Fragment> _stop = e.getStop();
            for (final Fragment destinationFragment : _stop) {
              String _string_1 = middle.toString();
              Integer _get = this.registry.get(destinationFragment.getName());
              String _plus_2 = ("execute[" + _get);
              String _plus_3 = (_plus_2 + "]!");
              transitions.add(new String[] { _string_1, startLocation, null, null, _plus_3, null });
            }
          }
          String _string_2 = e.getOperator().toString();
          boolean _equals_1 = Objects.equal(_string_2, "--|");
          if (_equals_1) {
            final List<Fragment> destinationList = IterableExtensions.<Fragment>toList(e.getStop());
            String currentLoc = middle.toString();
            int _size = destinationList.size();
            ExclusiveRange _doubleDotLessThan = new ExclusiveRange(0, _size, true);
            for (final Integer i : _doubleDotLessThan) {
              {
                final Fragment destinationFragment_1 = destinationList.get((i).intValue());
                int _size_1 = destinationList.size();
                int _minus = (_size_1 - 1);
                boolean _equals_2 = ((i).intValue() == _minus);
                if (_equals_2) {
                  Integer _get_1 = this.registry.get(destinationFragment_1.getName());
                  String _plus_4 = ("parallel[" + _get_1);
                  String _plus_5 = (_plus_4 + "]!");
                  transitions.add(new String[] { currentLoc, startLocation, null, null, _plus_5, null });
                } else {
                  int _iD_2 = this.getID();
                  final String nextLoc = ("id" + Integer.valueOf(_iD_2));
                  locations.add(this.createLocation(nextLoc, null));
                  Integer _get_2 = this.registry.get(destinationFragment_1.getName());
                  String _plus_6 = ("parallel[" + _get_2);
                  String _plus_7 = (_plus_6 + "]!");
                  transitions.add(new String[] { currentLoc, nextLoc, null, null, _plus_7, null });
                  currentLoc = nextLoc;
                }
              }
            }
          }
          String _string_3 = e.getOperator().toString();
          boolean _equals_2 = Objects.equal(_string_3, "--::");
          if (_equals_2) {
            final List<Fragment> destinationFragments = IterableExtensions.<Fragment>toList(e.getStop());
            String currentLoc_1 = middle.toString();
            int _size_1 = destinationFragments.size();
            ExclusiveRange _doubleDotLessThan_1 = new ExclusiveRange(0, _size_1, true);
            for (final Integer i_1 : _doubleDotLessThan_1) {
              {
                final Fragment destinationFragment_1 = destinationFragments.get((i_1).intValue());
                int _size_2 = destinationFragments.size();
                int _minus = (_size_2 - 1);
                boolean _equals_3 = ((i_1).intValue() == _minus);
                if (_equals_3) {
                  Integer _get_1 = this.registry.get(destinationFragment_1.getName());
                  String _plus_4 = ("execute[" + _get_1);
                  String _plus_5 = (_plus_4 + "]!");
                  transitions.add(new String[] { currentLoc_1, startLocation, null, null, _plus_5, null });
                } else {
                  int _iD_2 = this.getID();
                  final String nextLoc = ("id" + Integer.valueOf(_iD_2));
                  locations.add(this.createLocation(nextLoc, null));
                  Integer _get_2 = this.registry.get(destinationFragment_1.getName());
                  String _plus_6 = ("execute[" + _get_2);
                  String _plus_7 = (_plus_6 + "]!");
                  transitions.add(new String[] { currentLoc_1, nextLoc, null, null, _plus_7, null });
                  currentLoc_1 = nextLoc;
                }
              }
            }
          }
        }
      }
      final CommonResult commonResult = this.commonPart("", middle, this.registry.get(f.getName()).toString(), s, f, Boolean.valueOf(leafFragment), "");
      locations.addAll(commonResult.locations);
      transitions.addAll(commonResult.transitions);
      if (((leafFragment == false) && (!Objects.equal(startLocation, "")))) {
        String _xifexpression = null;
        boolean _notEquals = (!Objects.equal(commonResult.initLocationSpecial, null));
        if (_notEquals) {
          _xifexpression = commonResult.initLocationSpecial;
        } else {
          _xifexpression = commonResult.initLocation;
        }
        final String targetLocation = _xifexpression;
        transitions.add(new String[] { startLocation, targetLocation, null, null, null, null });
      }
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("<template>");
      _builder.newLine();
      _builder.append("<name x=\"5\" y=\"5\"> ");
      String _name = f.getName();
      _builder.append(_name);
      _builder.append(" </name>");
      _builder.newLineIfNotEmpty();
      _builder.append("<declaration></declaration>");
      _builder.newLine();
      _builder.newLine();
      {
        for(final String location : locations) {
          _builder.append(location);
          _builder.newLineIfNotEmpty();
        }
      }
      _builder.newLine();
      {
        boolean _notEquals_1 = (!Objects.equal(commonResult.initLocationSpecial, null));
        if (_notEquals_1) {
          _builder.append("<init ref=\"");
          _builder.append(commonResult.initLocationSpecial);
          _builder.append("\"/>");
          _builder.newLineIfNotEmpty();
        } else {
          _builder.append("<init ref=\"");
          _builder.append(commonResult.initLocation);
          _builder.append("\"/>");
          _builder.newLineIfNotEmpty();
        }
      }
      _builder.newLine();
      {
        for(final String[] transition : transitions) {
          String _createTransition = this.createTransition(transition[0], transition[1], transition[2], transition[3], transition[4], transition[5]);
          _builder.append(_createTransition);
          _builder.newLineIfNotEmpty();
        }
      }
      _builder.append("</template>");
      _builder.newLine();
      _xblockexpression = _builder;
    }
    return _xblockexpression;
  }

  public CommonResult commonPart(final String initLocation, final String terminalID, final String fragmentID, final Structure s, final Fragment f, final Boolean leafFragment, final String startLocation) {
    int _iD = this.getID();
    final String waitingLocation = ("id" + Integer.valueOf(_iD));
    int _iD_1 = this.getID();
    final String executingLocation = ("id" + Integer.valueOf(_iD_1));
    final ArrayList<String> locations = new ArrayList<String>();
    final ArrayList<String[]> transitions = new ArrayList<String[]>();
    locations.add(this.createLocation(waitingLocation, null));
    locations.add(this.createLocation(executingLocation, "committed"));
    if (((leafFragment).booleanValue() == false)) {
      transitions.add(new String[] { executingLocation, terminalID, null, null, (("completed[" + fragmentID) + "]!"), (("prepareExecution(" + fragmentID) + ")") });
    } else {
      transitions.add(new String[] { executingLocation, waitingLocation, null, null, (("completed[" + fragmentID) + "]!"), (("prepareExecution(" + fragmentID) + ")") });
    }
    String initLocationSpecial = null;
    String _init = f.getInit();
    boolean _equals = Objects.equal(_init, "init");
    if (_equals) {
      int _iD_2 = this.getID();
      String _plus = ("id" + Integer.valueOf(_iD_2));
      initLocationSpecial = _plus;
      locations.add(this.createLocation(initLocationSpecial, null));
      transitions.add(new String[] { initLocationSpecial, executingLocation, null, null, null, null });
      String actualWaitingLocation = initLocationSpecial;
      final Function1<Edge, Boolean> _function = (Edge it) -> {
        return Boolean.valueOf((Objects.equal(it.getOperator().toString(), "--|") && it.getStop().contains(f)));
      };
      final Iterable<Edge> parallelEdges = IterableExtensions.<Edge>filter(s.getEdges(), _function);
      boolean _isEmpty = IterableExtensions.isEmpty(parallelEdges);
      boolean _equals_1 = (_isEmpty == false);
      if (_equals_1) {
        transitions.add(new String[] { actualWaitingLocation, executingLocation, null, null, (("parallel[" + fragmentID) + "]?"), null });
      }
      return new CommonResult(locations, transitions, initLocationSpecial, actualWaitingLocation);
    } else {
      transitions.add(new String[] { waitingLocation, executingLocation, null, null, (("execute[" + fragmentID) + "]?"), null });
      final Function1<Edge, Boolean> _function_1 = (Edge it) -> {
        return Boolean.valueOf((Objects.equal(it.getOperator().toString(), "--|") && it.getStop().contains(f)));
      };
      final Iterable<Edge> parallelEdges_1 = IterableExtensions.<Edge>filter(s.getEdges(), _function_1);
      boolean _isEmpty_1 = IterableExtensions.isEmpty(parallelEdges_1);
      boolean _equals_2 = (_isEmpty_1 == false);
      if (_equals_2) {
        transitions.add(new String[] { waitingLocation, executingLocation, null, null, (("parallel[" + fragmentID) + "]?"), null });
      }
      if ((leafFragment).booleanValue()) {
      }
      return new CommonResult(locations, transitions, null, waitingLocation);
    }
  }

  public int getID() {
    return this.id = (this.id + 1);
  }

  public String getLastID() {
    return ("id" + Integer.valueOf(this.id));
  }

  public String createLocation(final String i, final String type) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<location id=\"");
    _builder.append(i);
    _builder.append("\">");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("<name>");
    _builder.append(i, "\t");
    _builder.append("</name>");
    _builder.newLineIfNotEmpty();
    {
      boolean _notEquals = (!Objects.equal(type, null));
      if (_notEquals) {
        _builder.append("\t");
        _builder.append("<");
        _builder.append(type, "\t");
        _builder.append("/>");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("</location>");
    return _builder.toString();
  }

  public String createTransition(final String s, final String t, final String select, final String guard, final String sync, final String ass) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<transition>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<source ref=\"");
    _builder.append(s, "\t");
    _builder.append("\"/>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("<target ref=\"");
    _builder.append(t, "\t");
    _builder.append("\"/>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    {
      boolean _notEquals = (!Objects.equal(select, null));
      if (_notEquals) {
        _builder.append("\t<label kind=\"select\" >");
        _builder.append(select, "\t");
        _builder.append("</label>");
      }
    }
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    {
      boolean _notEquals_1 = (!Objects.equal(guard, null));
      if (_notEquals_1) {
        _builder.append("\t<label kind=\"guard\" >");
        _builder.append(guard, "\t");
        _builder.append("</label>");
      }
    }
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    {
      boolean _notEquals_2 = (!Objects.equal(sync, null));
      if (_notEquals_2) {
        _builder.append("\t<label kind=\"synchronisation\" >");
        _builder.append(sync, "\t");
        _builder.append("</label>");
      }
    }
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    {
      boolean _notEquals_3 = (!Objects.equal(ass, null));
      if (_notEquals_3) {
        _builder.append("\t<label kind=\"assignment\" >");
        _builder.append(ass, "\t");
        _builder.append("</label>");
      }
    }
    _builder.newLineIfNotEmpty();
    _builder.append("</transition>");
    _builder.newLine();
    return _builder.toString();
  }

  public String CloudExecutor() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<template>");
    _builder.newLine();
    _builder.append("<name>CloudExecutor</name>");
    _builder.newLine();
    _builder.append("<declaration>");
    _builder.newLine();
    _builder.append("void executeFragment(int fragmentId) {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("// Calculate energy consumption based on fragment characteristics");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("int computationEnergy = Info[fragmentId].instructions * cloudEnergyPerInstruction;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("int memoryEnergy = Info[fragmentId].memory * cloudEnergyPerMemoryUnit;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("int communicationEnergy = Info[fragmentId].communicationData * cloudEnergyPerDataUnit;");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("// Update total energy consumption");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("totalEnergyConsumed += computationEnergy + memoryEnergy + communicationEnergy;");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("// Update execution time");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("executionTime += ((Info[fragmentId].instructions * 10) / cloudInstructions);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("if(executionTime == 0) executionTime = 1; // Minimum execution time");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("// Mark fragment as completed");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("fragmentsCompleted[fragmentId] = true;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.append("</declaration>");
    _builder.newLine();
    _builder.newLine();
    int _iD = this.getID();
    final String idle = ("id" + Integer.valueOf(_iD));
    _builder.newLineIfNotEmpty();
    int _iD_1 = this.getID();
    final String executing = ("id" + Integer.valueOf(_iD_1));
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    String _createLocation = this.createLocation(idle, null);
    _builder.append(_createLocation);
    _builder.newLineIfNotEmpty();
    String _createLocation_1 = this.createLocation(executing, "committed");
    _builder.append(_createLocation_1);
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("<init ref=\"");
    _builder.append(idle);
    _builder.append("\"/>");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    String _createTransition = this.createTransition(idle, executing, "f : id_t", null, "completed[f]?", "currentFragment = f");
    _builder.append(_createTransition);
    _builder.newLineIfNotEmpty();
    String _createTransition_1 = this.createTransition(executing, idle, null, null, null, "executeFragment(currentFragment)");
    _builder.append(_createTransition_1);
    _builder.newLineIfNotEmpty();
    _builder.append("</template>");
    _builder.newLine();
    return _builder.toString();
  }

  public String EnergyMonitor() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<template>");
    _builder.newLine();
    _builder.append("<name>EnergyMonitor</name>");
    _builder.newLine();
    _builder.append("<declaration>");
    _builder.newLine();
    _builder.append("// Energy monitoring functions");
    _builder.newLine();
    _builder.append("bool allFragmentsCompleted() {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("int i;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("for(i = 0; i &lt; N; i++) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("if(!fragmentsCompleted[i]) return false;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("return true;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("int calculateTotalEnergy() {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("return totalEnergyConsumed;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("int calculateAverageEnergyPerFragment() {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("if(N > 0) return totalEnergyConsumed / N;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("return 0;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.append("</declaration>");
    _builder.newLine();
    _builder.newLine();
    int _iD = this.getID();
    final String monitoring = ("id" + Integer.valueOf(_iD));
    _builder.newLineIfNotEmpty();
    int _iD_1 = this.getID();
    final String finished = ("id" + Integer.valueOf(_iD_1));
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    String _createLocation = this.createLocation(monitoring, null);
    _builder.append(_createLocation);
    _builder.newLineIfNotEmpty();
    String _createLocation_1 = this.createLocation(finished, null);
    _builder.append(_createLocation_1);
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("<init ref=\"");
    _builder.append(monitoring);
    _builder.append("\"/>");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    String _createTransition = this.createTransition(monitoring, finished, null, "allFragmentsCompleted()", null, "finalEnergyConsumption = calculateTotalEnergy()");
    _builder.append(_createTransition);
    _builder.newLineIfNotEmpty();
    _builder.append("</template>");
    _builder.newLine();
    return _builder.toString();
  }

  public String GlobalDeclarations(final Application a, final Resource r) {
    String _xblockexpression = null;
    {
      final Cloud cloud = IterableExtensions.<Cloud>last(Iterables.<Cloud>filter(IteratorExtensions.<EObject>toIterable(r.getAllContents()), Cloud.class));
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("// Cloud-only energy consumption model");
      _builder.newLine();
      _builder.append("const int N=");
      int _size = a.getFragments().size();
      _builder.append(_size);
      _builder.append(";");
      _builder.newLineIfNotEmpty();
      _builder.append("typedef int[0, N-1] id_t;");
      _builder.newLine();
      _builder.newLine();
      _builder.append("// Cloud computing parameters");
      _builder.newLine();
      _builder.append("const int cloudInstructions=");
      int _cpuInstructions = cloud.getCpuInstructions();
      _builder.append(_cpuInstructions);
      _builder.append(";");
      _builder.newLineIfNotEmpty();
      _builder.newLine();
      _builder.append("// Energy consumption parameters (units: millijoules)");
      _builder.newLine();
      _builder.append("const int cloudEnergyPerInstruction = ");
      int _energyPerInstruction = cloud.getEnergyPerInstruction();
      _builder.append(_energyPerInstruction);
      _builder.append(";    // mJ per instruction");
      _builder.newLineIfNotEmpty();
      _builder.append("const int cloudEnergyPerMemoryUnit = ");
      int _energyPerMemoryUnit = cloud.getEnergyPerMemoryUnit();
      _builder.append(_energyPerMemoryUnit);
      _builder.append(";     // mJ per memory unit");
      _builder.newLineIfNotEmpty();
      _builder.append("const int cloudEnergyPerDataUnit = ");
      int _energyPerDataUnit = cloud.getEnergyPerDataUnit();
      _builder.append(_energyPerDataUnit);
      _builder.append(";       // mJ per communication data unit");
      _builder.newLineIfNotEmpty();
      _builder.newLine();
      _builder.append("// Communication channels");
      _builder.newLine();
      _builder.append("chan execute[N], completed[N], parallel[N];");
      _builder.newLine();
      _builder.newLine();
      _builder.append("// Energy tracking variables");
      _builder.newLine();
      _builder.append("int totalEnergyConsumed = 0;");
      _builder.newLine();
      _builder.append("int finalEnergyConsumption = 0;");
      _builder.newLine();
      _builder.append("int executionTime = 0;");
      _builder.newLine();
      _builder.newLine();
      _builder.append("// Fragment tracking");
      _builder.newLine();
      _builder.append("int currentFragment;");
      _builder.newLine();
      _builder.append("bool fragmentsCompleted[N];");
      _builder.newLine();
      _builder.append("int fragmentsExecuted = 0;");
      _builder.newLine();
      _builder.newLine();
      _builder.append("// Fragment information structure");
      _builder.newLine();
      _builder.append("typedef struct {");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("int instructions;           // Number of instructions to execute");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("int memory;                // Memory requirements");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("int communicationData;     // Data transfer requirements");
      _builder.newLine();
      _builder.append("} FragmentInfo;");
      _builder.newLine();
      _builder.newLine();
      _builder.append("const FragmentInfo Info[N] = {");
      _builder.newLine();
      {
        EList<Fragment> _fragments = a.getFragments();
        for(final Fragment f : _fragments) {
          _builder.append("\t");
          _builder.append("{");
          int _instructions = f.getInstructions();
          _builder.append(_instructions, "\t");
          _builder.append(", ");
          int _memory = f.getMemory();
          _builder.append(_memory, "\t");
          _builder.append(", ");
          int _communicationData = f.getCommunicationData();
          _builder.append(_communicationData, "\t");
          _builder.append("}");
          _builder.newLineIfNotEmpty();
          _builder.append("\t");
          {
            String _name = f.getName();
            String _name_1 = IterableExtensions.<Fragment>last(a.getFragments()).getName();
            boolean _notEquals = (!Objects.equal(_name, _name_1));
            if (_notEquals) {
              _builder.append(",");
            }
          }
          _builder.newLineIfNotEmpty();
        }
      }
      _builder.append("};");
      _builder.newLine();
      _builder.newLine();
      _builder.newLine();
      _builder.newLine();
      _builder.append("// Helper functions");
      _builder.newLine();
      _builder.append("void prepareExecution(int fragmentId) {");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("// Initialize fragment for execution");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("fragmentsCompleted[fragmentId] = false;");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      _xblockexpression = _builder.toString();
    }
    return _xblockexpression;
  }
}
