package org.xtext.generator;

import org.eclipse.xtend2.lib.StringConcatenation;

@SuppressWarnings("all")
public class Utils {
  public static CharSequence Policy() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("\t\t");
    _builder.append("<template><name>Policy</name>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<declaration>int x;");
    _builder.newLine();
    _builder.append("/*");
    _builder.newLine();
    _builder.append("0=null");
    _builder.newLine();
    _builder.append("1=loadL  // load on cloud device");
    _builder.newLine();
    _builder.append("5=back");
    _builder.newLine();
    _builder.append("6=restore");
    _builder.newLine();
    _builder.append("8=disposeR");
    _builder.newLine();
    _builder.append("*/");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</declaration>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<location id=\"id15\" x=\"0\" y=\"128\"><committed/></location>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<location id=\"id16\" x=\"0\" y=\"0\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<init ref=\"id16\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<!-- Dispose operation -->");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<transition>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<source ref=\"id15\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<target ref=\"id16\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<label kind=\"guard\" x=\"16\" y=\"-352\">operation[x]!=0 and operation[x]==5</label>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<label kind=\"synchronisation\" x=\"32\" y=\"-328\">disposeR[x]!</label>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<label kind=\"assignment\" x=\"32\" y=\"-304\">operation[x]=8</label>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<nail x=\"200\" y=\"-280\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<nail x=\"8\" y=\"-304\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</transition>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<!-- Load on cloud -->");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<transition>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<source ref=\"id15\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<target ref=\"id16\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<label kind=\"guard\" x=\"-768\" y=\"-24\">operation[x]==0</label>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<label kind=\"synchronisation\" x=\"-704\" y=\"40\">loadL[x]!</label>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<label kind=\"assignment\" x=\"-688\" y=\"0\">operation[x]=1</label>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<nail x=\"-640\" y=\"120\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<nail x=\"-632\" y=\"-40\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</transition>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<!-- Restore -->");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<transition>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<source ref=\"id15\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<target ref=\"id16\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<label kind=\"guard\" x=\"256\" y=\"232\">operation[x]!=0 and (operation[x]==1 or operation[x]==7)</label>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<label kind=\"synchronisation\" x=\"320\" y=\"264\">restore[x]!</label>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<label kind=\"assignment\" x=\"312\" y=\"288\">operation[x]=6</label>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<nail x=\"360\" y=\"344\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<nail x=\"360\" y=\"208\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</transition>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<!-- Back -->");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<transition>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<source ref=\"id15\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<target ref=\"id16\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<label kind=\"guard\" x=\"-976\" y=\"256\">operation[x]!=0 and (operation[x]==1 or operation[x]==7)</label>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<label kind=\"synchronisation\" x=\"-480\" y=\"296\">back[x]!</label>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<label kind=\"assignment\" x=\"-504\" y=\"320\">operation[x]=5</label>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<nail x=\"-456\" y=\"376\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<nail x=\"-448\" y=\"224\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</transition>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<!-- Policy select -->");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<transition>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<source ref=\"id16\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<target ref=\"id15\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<label kind=\"select\" x=\"-56\" y=\"32\">e : id_t</label>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<label kind=\"guard\" x=\"-104\" y=\"16\">(fragmentToCompute!=e or instructionsNumber[e]>0) and p==true</label>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<label kind=\"synchronisation\" x=\"-56\" y=\"48\">policy[e]?</label>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<label kind=\"assignment\" x=\"-40\" y=\"80\">x=e, p=false</label>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</transition>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</template>");
    _builder.newLine();
    return _builder;
  }
}
