/*
 * generated by Xtext 2.34.0
 */
package org.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.MCCc.ui.internal.MCCcActivator;

public class MCCUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MCCcActivator.getInstance().getInjector("org.xtext.MCC");
	}

}
