/*
 * generated by Xtext 2.34.0
 */
package org.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMCCScopeProvider extends DelegatingScopeProvider {
}
