/*
 * generated by Xtext 2.34.0
 */
grammar InternalMCC;

options {
	superClass=AbstractInternalContentAssistParser;
}

@lexer::header {
package org.xtext.ide.contentassist.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.Lexer;
}

@parser::header {
package org.xtext.ide.contentassist.antlr.internal;

import java.io.InputStream;
import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.DFA;
import org.xtext.services.MCCGrammarAccess;

}
@parser::members {
	private MCCGrammarAccess grammarAccess;

	public void setGrammarAccess(MCCGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}

	@Override
	protected Grammar getGrammar() {
		return grammarAccess.getGrammar();
	}

	@Override
	protected String getValueForTokenName(String tokenName) {
		return tokenName;
	}
}

// Entry rule entryRuleModel
entryRuleModel
:
{ before(grammarAccess.getModelRule()); }
	 ruleModel
{ after(grammarAccess.getModelRule()); } 
	 EOF 
;

// Rule Model
ruleModel 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getModelAccess().getAlternatives()); }
		(rule__Model__Alternatives)*
		{ after(grammarAccess.getModelAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleDevice
entryRuleDevice
:
{ before(grammarAccess.getDeviceRule()); }
	 ruleDevice
{ after(grammarAccess.getDeviceRule()); } 
	 EOF 
;

// Rule Device
ruleDevice 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getDeviceAccess().getAlternatives()); }
		(rule__Device__Alternatives)
		{ after(grammarAccess.getDeviceAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleCloud
entryRuleCloud
:
{ before(grammarAccess.getCloudRule()); }
	 ruleCloud
{ after(grammarAccess.getCloudRule()); } 
	 EOF 
;

// Rule Cloud
ruleCloud 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getCloudAccess().getGroup()); }
		(rule__Cloud__Group__0)
		{ after(grammarAccess.getCloudAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleDummyDevice
entryRuleDummyDevice
:
{ before(grammarAccess.getDummyDeviceRule()); }
	 ruleDummyDevice
{ after(grammarAccess.getDummyDeviceRule()); } 
	 EOF 
;

// Rule DummyDevice
ruleDummyDevice 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getDummyDeviceAccess().getGroup()); }
		(rule__DummyDevice__Group__0)
		{ after(grammarAccess.getDummyDeviceAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleApplication
entryRuleApplication
:
{ before(grammarAccess.getApplicationRule()); }
	 ruleApplication
{ after(grammarAccess.getApplicationRule()); } 
	 EOF 
;

// Rule Application
ruleApplication 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getApplicationAccess().getGroup()); }
		(rule__Application__Group__0)
		{ after(grammarAccess.getApplicationAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleStructure
entryRuleStructure
:
{ before(grammarAccess.getStructureRule()); }
	 ruleStructure
{ after(grammarAccess.getStructureRule()); } 
	 EOF 
;

// Rule Structure
ruleStructure 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getStructureAccess().getGroup()); }
		(rule__Structure__Group__0)
		{ after(grammarAccess.getStructureAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleEdge
entryRuleEdge
:
{ before(grammarAccess.getEdgeRule()); }
	 ruleEdge
{ after(grammarAccess.getEdgeRule()); } 
	 EOF 
;

// Rule Edge
ruleEdge 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getEdgeAccess().getGroup()); }
		(rule__Edge__Group__0)
		{ after(grammarAccess.getEdgeAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleFragment
entryRuleFragment
:
{ before(grammarAccess.getFragmentRule()); }
	 ruleFragment
{ after(grammarAccess.getFragmentRule()); } 
	 EOF 
;

// Rule Fragment
ruleFragment 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getFragmentAccess().getGroup()); }
		(rule__Fragment__Group__0)
		{ after(grammarAccess.getFragmentAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleSystem
entryRuleSystem
:
{ before(grammarAccess.getSystemRule()); }
	 ruleSystem
{ after(grammarAccess.getSystemRule()); } 
	 EOF 
;

// Rule System
ruleSystem 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getSystemAccess().getGroup()); }
		(rule__System__Group__0)
		{ after(grammarAccess.getSystemAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Rule Operator
ruleOperator
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getOperatorAccess().getAlternatives()); }
		(rule__Operator__Alternatives)
		{ after(grammarAccess.getOperatorAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getModelAccess().getDevicesAssignment_0()); }
		(rule__Model__DevicesAssignment_0)
		{ after(grammarAccess.getModelAccess().getDevicesAssignment_0()); }
	)
	|
	(
		{ before(grammarAccess.getModelAccess().getApplicationsAssignment_1()); }
		(rule__Model__ApplicationsAssignment_1)
		{ after(grammarAccess.getModelAccess().getApplicationsAssignment_1()); }
	)
	|
	(
		{ before(grammarAccess.getModelAccess().getSystemsAssignment_2()); }
		(rule__Model__SystemsAssignment_2)
		{ after(grammarAccess.getModelAccess().getSystemsAssignment_2()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Device__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getDeviceAccess().getCloudParserRuleCall_0()); }
		ruleCloud
		{ after(grammarAccess.getDeviceAccess().getCloudParserRuleCall_0()); }
	)
	|
	(
		{ before(grammarAccess.getDeviceAccess().getDummyDeviceParserRuleCall_1()); }
		ruleDummyDevice
		{ after(grammarAccess.getDeviceAccess().getDummyDeviceParserRuleCall_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Operator__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getOperatorAccess().getNDCEnumLiteralDeclaration_0()); }
		('-->')
		{ after(grammarAccess.getOperatorAccess().getNDCEnumLiteralDeclaration_0()); }
	)
	|
	(
		{ before(grammarAccess.getOperatorAccess().getPAREnumLiteralDeclaration_1()); }
		('--|')
		{ after(grammarAccess.getOperatorAccess().getPAREnumLiteralDeclaration_1()); }
	)
	|
	(
		{ before(grammarAccess.getOperatorAccess().getSEQEnumLiteralDeclaration_2()); }
		('--::')
		{ after(grammarAccess.getOperatorAccess().getSEQEnumLiteralDeclaration_2()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Cloud__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Cloud__Group__0__Impl
	rule__Cloud__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Cloud__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCloudAccess().getCloudKeyword_0()); }
	'Cloud'
	{ after(grammarAccess.getCloudAccess().getCloudKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Cloud__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Cloud__Group__1__Impl
	rule__Cloud__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Cloud__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCloudAccess().getNameAssignment_1()); }
	(rule__Cloud__NameAssignment_1)
	{ after(grammarAccess.getCloudAccess().getNameAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Cloud__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Cloud__Group__2__Impl
	rule__Cloud__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Cloud__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCloudAccess().getLeftSquareBracketKeyword_2()); }
	'['
	{ after(grammarAccess.getCloudAccess().getLeftSquareBracketKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Cloud__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Cloud__Group__3__Impl
	rule__Cloud__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Cloud__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCloudAccess().getCpuInstructionsAssignment_3()); }
	(rule__Cloud__CpuInstructionsAssignment_3)
	{ after(grammarAccess.getCloudAccess().getCpuInstructionsAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Cloud__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Cloud__Group__4__Impl
	rule__Cloud__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Cloud__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCloudAccess().getCommaKeyword_4()); }
	','
	{ after(grammarAccess.getCloudAccess().getCommaKeyword_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Cloud__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Cloud__Group__5__Impl
	rule__Cloud__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__Cloud__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCloudAccess().getEnergyPerInstructionAssignment_5()); }
	(rule__Cloud__EnergyPerInstructionAssignment_5)
	{ after(grammarAccess.getCloudAccess().getEnergyPerInstructionAssignment_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Cloud__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Cloud__Group__6__Impl
	rule__Cloud__Group__7
;
finally {
	restoreStackSize(stackSize);
}

rule__Cloud__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCloudAccess().getCommaKeyword_6()); }
	','
	{ after(grammarAccess.getCloudAccess().getCommaKeyword_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Cloud__Group__7
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Cloud__Group__7__Impl
	rule__Cloud__Group__8
;
finally {
	restoreStackSize(stackSize);
}

rule__Cloud__Group__7__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCloudAccess().getEnergyPerMemoryUnitAssignment_7()); }
	(rule__Cloud__EnergyPerMemoryUnitAssignment_7)
	{ after(grammarAccess.getCloudAccess().getEnergyPerMemoryUnitAssignment_7()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Cloud__Group__8
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Cloud__Group__8__Impl
	rule__Cloud__Group__9
;
finally {
	restoreStackSize(stackSize);
}

rule__Cloud__Group__8__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCloudAccess().getCommaKeyword_8()); }
	','
	{ after(grammarAccess.getCloudAccess().getCommaKeyword_8()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Cloud__Group__9
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Cloud__Group__9__Impl
	rule__Cloud__Group__10
;
finally {
	restoreStackSize(stackSize);
}

rule__Cloud__Group__9__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCloudAccess().getEnergyPerDataUnitAssignment_9()); }
	(rule__Cloud__EnergyPerDataUnitAssignment_9)
	{ after(grammarAccess.getCloudAccess().getEnergyPerDataUnitAssignment_9()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Cloud__Group__10
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Cloud__Group__10__Impl
	rule__Cloud__Group__11
;
finally {
	restoreStackSize(stackSize);
}

rule__Cloud__Group__10__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCloudAccess().getCommaKeyword_10()); }
	','
	{ after(grammarAccess.getCloudAccess().getCommaKeyword_10()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Cloud__Group__11
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Cloud__Group__11__Impl
	rule__Cloud__Group__12
;
finally {
	restoreStackSize(stackSize);
}

rule__Cloud__Group__11__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCloudAccess().getApplicationsAssignment_11()); }
	(rule__Cloud__ApplicationsAssignment_11)
	{ after(grammarAccess.getCloudAccess().getApplicationsAssignment_11()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Cloud__Group__12
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Cloud__Group__12__Impl
	rule__Cloud__Group__13
;
finally {
	restoreStackSize(stackSize);
}

rule__Cloud__Group__12__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCloudAccess().getRightSquareBracketKeyword_12()); }
	']'
	{ after(grammarAccess.getCloudAccess().getRightSquareBracketKeyword_12()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Cloud__Group__13
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Cloud__Group__13__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Cloud__Group__13__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCloudAccess().getSemicolonKeyword_13()); }
	';'
	{ after(grammarAccess.getCloudAccess().getSemicolonKeyword_13()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__DummyDevice__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__DummyDevice__Group__0__Impl
	rule__DummyDevice__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__DummyDevice__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDummyDeviceAccess().getDummyDeviceKeyword_0()); }
	'DummyDevice'
	{ after(grammarAccess.getDummyDeviceAccess().getDummyDeviceKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__DummyDevice__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__DummyDevice__Group__1__Impl
	rule__DummyDevice__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__DummyDevice__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDummyDeviceAccess().getNameAssignment_1()); }
	(rule__DummyDevice__NameAssignment_1)
	{ after(grammarAccess.getDummyDeviceAccess().getNameAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__DummyDevice__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__DummyDevice__Group__2__Impl
	rule__DummyDevice__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__DummyDevice__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDummyDeviceAccess().getLeftSquareBracketKeyword_2()); }
	'['
	{ after(grammarAccess.getDummyDeviceAccess().getLeftSquareBracketKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__DummyDevice__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__DummyDevice__Group__3__Impl
	rule__DummyDevice__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__DummyDevice__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDummyDeviceAccess().getApplicationsAssignment_3()); }
	(rule__DummyDevice__ApplicationsAssignment_3)
	{ after(grammarAccess.getDummyDeviceAccess().getApplicationsAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__DummyDevice__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__DummyDevice__Group__4__Impl
	rule__DummyDevice__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__DummyDevice__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDummyDeviceAccess().getRightSquareBracketKeyword_4()); }
	']'
	{ after(grammarAccess.getDummyDeviceAccess().getRightSquareBracketKeyword_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__DummyDevice__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__DummyDevice__Group__5__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__DummyDevice__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDummyDeviceAccess().getSemicolonKeyword_5()); }
	';'
	{ after(grammarAccess.getDummyDeviceAccess().getSemicolonKeyword_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Application__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Application__Group__0__Impl
	rule__Application__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Application__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getApplicationAccess().getApplicationKeyword_0()); }
	'Application'
	{ after(grammarAccess.getApplicationAccess().getApplicationKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Application__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Application__Group__1__Impl
	rule__Application__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Application__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getApplicationAccess().getNameAssignment_1()); }
	(rule__Application__NameAssignment_1)
	{ after(grammarAccess.getApplicationAccess().getNameAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Application__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Application__Group__2__Impl
	rule__Application__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Application__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getApplicationAccess().getLeftCurlyBracketKeyword_2()); }
	'{'
	{ after(grammarAccess.getApplicationAccess().getLeftCurlyBracketKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Application__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Application__Group__3__Impl
	rule__Application__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Application__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	(
		{ before(grammarAccess.getApplicationAccess().getFragmentsAssignment_3()); }
		(rule__Application__FragmentsAssignment_3)
		{ after(grammarAccess.getApplicationAccess().getFragmentsAssignment_3()); }
	)
	(
		{ before(grammarAccess.getApplicationAccess().getFragmentsAssignment_3()); }
		(rule__Application__FragmentsAssignment_3)*
		{ after(grammarAccess.getApplicationAccess().getFragmentsAssignment_3()); }
	)
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Application__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Application__Group__4__Impl
	rule__Application__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Application__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getApplicationAccess().getStructureAssignment_4()); }
	(rule__Application__StructureAssignment_4)
	{ after(grammarAccess.getApplicationAccess().getStructureAssignment_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Application__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Application__Group__5__Impl
	rule__Application__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__Application__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getApplicationAccess().getRightCurlyBracketKeyword_5()); }
	'}'
	{ after(grammarAccess.getApplicationAccess().getRightCurlyBracketKeyword_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Application__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Application__Group__6__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Application__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getApplicationAccess().getSemicolonKeyword_6()); }
	';'
	{ after(grammarAccess.getApplicationAccess().getSemicolonKeyword_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Structure__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Structure__Group__0__Impl
	rule__Structure__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Structure__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getStructureAccess().getStructureKeyword_0()); }
	'Structure'
	{ after(grammarAccess.getStructureAccess().getStructureKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Structure__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Structure__Group__1__Impl
	rule__Structure__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Structure__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getStructureAccess().getNameAssignment_1()); }
	(rule__Structure__NameAssignment_1)
	{ after(grammarAccess.getStructureAccess().getNameAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Structure__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Structure__Group__2__Impl
	rule__Structure__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Structure__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getStructureAccess().getLeftSquareBracketKeyword_2()); }
	'['
	{ after(grammarAccess.getStructureAccess().getLeftSquareBracketKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Structure__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Structure__Group__3__Impl
	rule__Structure__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Structure__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	(
		{ before(grammarAccess.getStructureAccess().getEdgesAssignment_3()); }
		(rule__Structure__EdgesAssignment_3)
		{ after(grammarAccess.getStructureAccess().getEdgesAssignment_3()); }
	)
	(
		{ before(grammarAccess.getStructureAccess().getEdgesAssignment_3()); }
		(rule__Structure__EdgesAssignment_3)*
		{ after(grammarAccess.getStructureAccess().getEdgesAssignment_3()); }
	)
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Structure__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Structure__Group__4__Impl
	rule__Structure__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Structure__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getStructureAccess().getRightSquareBracketKeyword_4()); }
	']'
	{ after(grammarAccess.getStructureAccess().getRightSquareBracketKeyword_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Structure__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Structure__Group__5__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Structure__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getStructureAccess().getSemicolonKeyword_5()); }
	';'
	{ after(grammarAccess.getStructureAccess().getSemicolonKeyword_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Edge__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Edge__Group__0__Impl
	rule__Edge__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Edge__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEdgeAccess().getStartAssignment_0()); }
	(rule__Edge__StartAssignment_0)
	{ after(grammarAccess.getEdgeAccess().getStartAssignment_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Edge__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Edge__Group__1__Impl
	rule__Edge__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Edge__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEdgeAccess().getOperatorAssignment_1()); }
	(rule__Edge__OperatorAssignment_1)
	{ after(grammarAccess.getEdgeAccess().getOperatorAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Edge__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Edge__Group__2__Impl
	rule__Edge__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Edge__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEdgeAccess().getStopAssignment_2()); }
	(rule__Edge__StopAssignment_2)
	{ after(grammarAccess.getEdgeAccess().getStopAssignment_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Edge__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Edge__Group__3__Impl
	rule__Edge__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Edge__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEdgeAccess().getGroup_3()); }
	(rule__Edge__Group_3__0)*
	{ after(grammarAccess.getEdgeAccess().getGroup_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Edge__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Edge__Group__4__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Edge__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEdgeAccess().getSemicolonKeyword_4()); }
	';'
	{ after(grammarAccess.getEdgeAccess().getSemicolonKeyword_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Edge__Group_3__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Edge__Group_3__0__Impl
	rule__Edge__Group_3__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Edge__Group_3__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEdgeAccess().getCommaKeyword_3_0()); }
	','
	{ after(grammarAccess.getEdgeAccess().getCommaKeyword_3_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Edge__Group_3__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Edge__Group_3__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Edge__Group_3__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEdgeAccess().getStopAssignment_3_1()); }
	(rule__Edge__StopAssignment_3_1)
	{ after(grammarAccess.getEdgeAccess().getStopAssignment_3_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Fragment__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Fragment__Group__0__Impl
	rule__Fragment__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Fragment__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getFragmentAccess().getFragmentKeyword_0()); }
	'Fragment'
	{ after(grammarAccess.getFragmentAccess().getFragmentKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Fragment__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Fragment__Group__1__Impl
	rule__Fragment__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Fragment__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getFragmentAccess().getNameAssignment_1()); }
	(rule__Fragment__NameAssignment_1)
	{ after(grammarAccess.getFragmentAccess().getNameAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Fragment__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Fragment__Group__2__Impl
	rule__Fragment__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Fragment__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getFragmentAccess().getLeftSquareBracketKeyword_2()); }
	'['
	{ after(grammarAccess.getFragmentAccess().getLeftSquareBracketKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Fragment__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Fragment__Group__3__Impl
	rule__Fragment__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Fragment__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getFragmentAccess().getInstructionsAssignment_3()); }
	(rule__Fragment__InstructionsAssignment_3)
	{ after(grammarAccess.getFragmentAccess().getInstructionsAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Fragment__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Fragment__Group__4__Impl
	rule__Fragment__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Fragment__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getFragmentAccess().getCommaKeyword_4()); }
	','
	{ after(grammarAccess.getFragmentAccess().getCommaKeyword_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Fragment__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Fragment__Group__5__Impl
	rule__Fragment__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__Fragment__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getFragmentAccess().getMemoryAssignment_5()); }
	(rule__Fragment__MemoryAssignment_5)
	{ after(grammarAccess.getFragmentAccess().getMemoryAssignment_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Fragment__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Fragment__Group__6__Impl
	rule__Fragment__Group__7
;
finally {
	restoreStackSize(stackSize);
}

rule__Fragment__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getFragmentAccess().getCommaKeyword_6()); }
	','
	{ after(grammarAccess.getFragmentAccess().getCommaKeyword_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Fragment__Group__7
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Fragment__Group__7__Impl
	rule__Fragment__Group__8
;
finally {
	restoreStackSize(stackSize);
}

rule__Fragment__Group__7__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getFragmentAccess().getCommunicationDataAssignment_7()); }
	(rule__Fragment__CommunicationDataAssignment_7)
	{ after(grammarAccess.getFragmentAccess().getCommunicationDataAssignment_7()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Fragment__Group__8
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Fragment__Group__8__Impl
	rule__Fragment__Group__9
;
finally {
	restoreStackSize(stackSize);
}

rule__Fragment__Group__8__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getFragmentAccess().getRightSquareBracketKeyword_8()); }
	']'
	{ after(grammarAccess.getFragmentAccess().getRightSquareBracketKeyword_8()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Fragment__Group__9
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Fragment__Group__9__Impl
	rule__Fragment__Group__10
;
finally {
	restoreStackSize(stackSize);
}

rule__Fragment__Group__9__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getFragmentAccess().getInitAssignment_9()); }
	(rule__Fragment__InitAssignment_9)?
	{ after(grammarAccess.getFragmentAccess().getInitAssignment_9()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Fragment__Group__10
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Fragment__Group__10__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Fragment__Group__10__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getFragmentAccess().getSemicolonKeyword_10()); }
	';'
	{ after(grammarAccess.getFragmentAccess().getSemicolonKeyword_10()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__System__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__System__Group__0__Impl
	rule__System__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__System__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSystemAccess().getSystemKeyword_0()); }
	'System'
	{ after(grammarAccess.getSystemAccess().getSystemKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__System__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__System__Group__1__Impl
	rule__System__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__System__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSystemAccess().getNameAssignment_1()); }
	(rule__System__NameAssignment_1)
	{ after(grammarAccess.getSystemAccess().getNameAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__System__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__System__Group__2__Impl
	rule__System__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__System__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSystemAccess().getColonEqualsSignKeyword_2()); }
	':='
	{ after(grammarAccess.getSystemAccess().getColonEqualsSignKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__System__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__System__Group__3__Impl
	rule__System__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__System__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSystemAccess().getDevicesAssignment_3()); }
	(rule__System__DevicesAssignment_3)
	{ after(grammarAccess.getSystemAccess().getDevicesAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__System__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__System__Group__4__Impl
	rule__System__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__System__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSystemAccess().getGroup_4()); }
	(rule__System__Group_4__0)*
	{ after(grammarAccess.getSystemAccess().getGroup_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__System__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__System__Group__5__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__System__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSystemAccess().getSemicolonKeyword_5()); }
	';'
	{ after(grammarAccess.getSystemAccess().getSemicolonKeyword_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__System__Group_4__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__System__Group_4__0__Impl
	rule__System__Group_4__1
;
finally {
	restoreStackSize(stackSize);
}

rule__System__Group_4__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSystemAccess().getVerticalLineKeyword_4_0()); }
	'|'
	{ after(grammarAccess.getSystemAccess().getVerticalLineKeyword_4_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__System__Group_4__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__System__Group_4__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__System__Group_4__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSystemAccess().getDevicesAssignment_4_1()); }
	(rule__System__DevicesAssignment_4_1)
	{ after(grammarAccess.getSystemAccess().getDevicesAssignment_4_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Model__DevicesAssignment_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getModelAccess().getDevicesDeviceParserRuleCall_0_0()); }
		ruleDevice
		{ after(grammarAccess.getModelAccess().getDevicesDeviceParserRuleCall_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__ApplicationsAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getModelAccess().getApplicationsApplicationParserRuleCall_1_0()); }
		ruleApplication
		{ after(grammarAccess.getModelAccess().getApplicationsApplicationParserRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__SystemsAssignment_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getModelAccess().getSystemsSystemParserRuleCall_2_0()); }
		ruleSystem
		{ after(grammarAccess.getModelAccess().getSystemsSystemParserRuleCall_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Cloud__NameAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getCloudAccess().getNameIDTerminalRuleCall_1_0()); }
		RULE_ID
		{ after(grammarAccess.getCloudAccess().getNameIDTerminalRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Cloud__CpuInstructionsAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getCloudAccess().getCpuInstructionsINTTerminalRuleCall_3_0()); }
		RULE_INT
		{ after(grammarAccess.getCloudAccess().getCpuInstructionsINTTerminalRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Cloud__EnergyPerInstructionAssignment_5
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getCloudAccess().getEnergyPerInstructionINTTerminalRuleCall_5_0()); }
		RULE_INT
		{ after(grammarAccess.getCloudAccess().getEnergyPerInstructionINTTerminalRuleCall_5_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Cloud__EnergyPerMemoryUnitAssignment_7
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getCloudAccess().getEnergyPerMemoryUnitINTTerminalRuleCall_7_0()); }
		RULE_INT
		{ after(grammarAccess.getCloudAccess().getEnergyPerMemoryUnitINTTerminalRuleCall_7_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Cloud__EnergyPerDataUnitAssignment_9
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getCloudAccess().getEnergyPerDataUnitINTTerminalRuleCall_9_0()); }
		RULE_INT
		{ after(grammarAccess.getCloudAccess().getEnergyPerDataUnitINTTerminalRuleCall_9_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Cloud__ApplicationsAssignment_11
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getCloudAccess().getApplicationsApplicationCrossReference_11_0()); }
		(
			{ before(grammarAccess.getCloudAccess().getApplicationsApplicationIDTerminalRuleCall_11_0_1()); }
			RULE_ID
			{ after(grammarAccess.getCloudAccess().getApplicationsApplicationIDTerminalRuleCall_11_0_1()); }
		)
		{ after(grammarAccess.getCloudAccess().getApplicationsApplicationCrossReference_11_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__DummyDevice__NameAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getDummyDeviceAccess().getNameIDTerminalRuleCall_1_0()); }
		RULE_ID
		{ after(grammarAccess.getDummyDeviceAccess().getNameIDTerminalRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__DummyDevice__ApplicationsAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getDummyDeviceAccess().getApplicationsApplicationCrossReference_3_0()); }
		(
			{ before(grammarAccess.getDummyDeviceAccess().getApplicationsApplicationIDTerminalRuleCall_3_0_1()); }
			RULE_ID
			{ after(grammarAccess.getDummyDeviceAccess().getApplicationsApplicationIDTerminalRuleCall_3_0_1()); }
		)
		{ after(grammarAccess.getDummyDeviceAccess().getApplicationsApplicationCrossReference_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Application__NameAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getApplicationAccess().getNameIDTerminalRuleCall_1_0()); }
		RULE_ID
		{ after(grammarAccess.getApplicationAccess().getNameIDTerminalRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Application__FragmentsAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getApplicationAccess().getFragmentsFragmentParserRuleCall_3_0()); }
		ruleFragment
		{ after(grammarAccess.getApplicationAccess().getFragmentsFragmentParserRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Application__StructureAssignment_4
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getApplicationAccess().getStructureStructureParserRuleCall_4_0()); }
		ruleStructure
		{ after(grammarAccess.getApplicationAccess().getStructureStructureParserRuleCall_4_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Structure__NameAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getStructureAccess().getNameIDTerminalRuleCall_1_0()); }
		RULE_ID
		{ after(grammarAccess.getStructureAccess().getNameIDTerminalRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Structure__EdgesAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getStructureAccess().getEdgesEdgeParserRuleCall_3_0()); }
		ruleEdge
		{ after(grammarAccess.getStructureAccess().getEdgesEdgeParserRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Edge__StartAssignment_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEdgeAccess().getStartFragmentCrossReference_0_0()); }
		(
			{ before(grammarAccess.getEdgeAccess().getStartFragmentIDTerminalRuleCall_0_0_1()); }
			RULE_ID
			{ after(grammarAccess.getEdgeAccess().getStartFragmentIDTerminalRuleCall_0_0_1()); }
		)
		{ after(grammarAccess.getEdgeAccess().getStartFragmentCrossReference_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Edge__OperatorAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEdgeAccess().getOperatorOperatorEnumRuleCall_1_0()); }
		ruleOperator
		{ after(grammarAccess.getEdgeAccess().getOperatorOperatorEnumRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Edge__StopAssignment_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEdgeAccess().getStopFragmentCrossReference_2_0()); }
		(
			{ before(grammarAccess.getEdgeAccess().getStopFragmentIDTerminalRuleCall_2_0_1()); }
			RULE_ID
			{ after(grammarAccess.getEdgeAccess().getStopFragmentIDTerminalRuleCall_2_0_1()); }
		)
		{ after(grammarAccess.getEdgeAccess().getStopFragmentCrossReference_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Edge__StopAssignment_3_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEdgeAccess().getStopFragmentCrossReference_3_1_0()); }
		(
			{ before(grammarAccess.getEdgeAccess().getStopFragmentIDTerminalRuleCall_3_1_0_1()); }
			RULE_ID
			{ after(grammarAccess.getEdgeAccess().getStopFragmentIDTerminalRuleCall_3_1_0_1()); }
		)
		{ after(grammarAccess.getEdgeAccess().getStopFragmentCrossReference_3_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Fragment__NameAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getFragmentAccess().getNameIDTerminalRuleCall_1_0()); }
		RULE_ID
		{ after(grammarAccess.getFragmentAccess().getNameIDTerminalRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Fragment__InstructionsAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getFragmentAccess().getInstructionsINTTerminalRuleCall_3_0()); }
		RULE_INT
		{ after(grammarAccess.getFragmentAccess().getInstructionsINTTerminalRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Fragment__MemoryAssignment_5
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getFragmentAccess().getMemoryINTTerminalRuleCall_5_0()); }
		RULE_INT
		{ after(grammarAccess.getFragmentAccess().getMemoryINTTerminalRuleCall_5_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Fragment__CommunicationDataAssignment_7
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getFragmentAccess().getCommunicationDataINTTerminalRuleCall_7_0()); }
		RULE_INT
		{ after(grammarAccess.getFragmentAccess().getCommunicationDataINTTerminalRuleCall_7_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Fragment__InitAssignment_9
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getFragmentAccess().getInitInitKeyword_9_0()); }
		(
			{ before(grammarAccess.getFragmentAccess().getInitInitKeyword_9_0()); }
			'init'
			{ after(grammarAccess.getFragmentAccess().getInitInitKeyword_9_0()); }
		)
		{ after(grammarAccess.getFragmentAccess().getInitInitKeyword_9_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__System__NameAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getSystemAccess().getNameIDTerminalRuleCall_1_0()); }
		RULE_ID
		{ after(grammarAccess.getSystemAccess().getNameIDTerminalRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__System__DevicesAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getSystemAccess().getDevicesDeviceCrossReference_3_0()); }
		(
			{ before(grammarAccess.getSystemAccess().getDevicesDeviceIDTerminalRuleCall_3_0_1()); }
			RULE_ID
			{ after(grammarAccess.getSystemAccess().getDevicesDeviceIDTerminalRuleCall_3_0_1()); }
		)
		{ after(grammarAccess.getSystemAccess().getDevicesDeviceCrossReference_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__System__DevicesAssignment_4_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getSystemAccess().getDevicesDeviceCrossReference_4_1_0()); }
		(
			{ before(grammarAccess.getSystemAccess().getDevicesDeviceIDTerminalRuleCall_4_1_0_1()); }
			RULE_ID
			{ after(grammarAccess.getSystemAccess().getDevicesDeviceIDTerminalRuleCall_4_1_0_1()); }
		)
		{ after(grammarAccess.getSystemAccess().getDevicesDeviceCrossReference_4_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
