/**
 * generated by Xtext 2.34.0
 */
package org.xtext.mCC.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.mCC.Cloud;
import org.xtext.mCC.MCCPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Cloud</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mCC.impl.CloudImpl#getCpuInstructions <em>Cpu Instructions</em>}</li>
 *   <li>{@link org.xtext.mCC.impl.CloudImpl#getEnergyPerInstruction <em>Energy Per Instruction</em>}</li>
 *   <li>{@link org.xtext.mCC.impl.CloudImpl#getEnergyPerMemoryUnit <em>Energy Per Memory Unit</em>}</li>
 *   <li>{@link org.xtext.mCC.impl.CloudImpl#getEnergyPerDataUnit <em>Energy Per Data Unit</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CloudImpl extends DeviceImpl implements Cloud
{
  /**
   * The default value of the '{@link #getCpuInstructions() <em>Cpu Instructions</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCpuInstructions()
   * @generated
   * @ordered
   */
  protected static final int CPU_INSTRUCTIONS_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getCpuInstructions() <em>Cpu Instructions</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCpuInstructions()
   * @generated
   * @ordered
   */
  protected int cpuInstructions = CPU_INSTRUCTIONS_EDEFAULT;

  /**
   * The default value of the '{@link #getEnergyPerInstruction() <em>Energy Per Instruction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnergyPerInstruction()
   * @generated
   * @ordered
   */
  protected static final int ENERGY_PER_INSTRUCTION_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getEnergyPerInstruction() <em>Energy Per Instruction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnergyPerInstruction()
   * @generated
   * @ordered
   */
  protected int energyPerInstruction = ENERGY_PER_INSTRUCTION_EDEFAULT;

  /**
   * The default value of the '{@link #getEnergyPerMemoryUnit() <em>Energy Per Memory Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnergyPerMemoryUnit()
   * @generated
   * @ordered
   */
  protected static final int ENERGY_PER_MEMORY_UNIT_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getEnergyPerMemoryUnit() <em>Energy Per Memory Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnergyPerMemoryUnit()
   * @generated
   * @ordered
   */
  protected int energyPerMemoryUnit = ENERGY_PER_MEMORY_UNIT_EDEFAULT;

  /**
   * The default value of the '{@link #getEnergyPerDataUnit() <em>Energy Per Data Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnergyPerDataUnit()
   * @generated
   * @ordered
   */
  protected static final int ENERGY_PER_DATA_UNIT_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getEnergyPerDataUnit() <em>Energy Per Data Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnergyPerDataUnit()
   * @generated
   * @ordered
   */
  protected int energyPerDataUnit = ENERGY_PER_DATA_UNIT_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CloudImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MCCPackage.Literals.CLOUD;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getCpuInstructions()
  {
    return cpuInstructions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCpuInstructions(int newCpuInstructions)
  {
    int oldCpuInstructions = cpuInstructions;
    cpuInstructions = newCpuInstructions;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MCCPackage.CLOUD__CPU_INSTRUCTIONS, oldCpuInstructions, cpuInstructions));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getEnergyPerInstruction()
  {
    return energyPerInstruction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEnergyPerInstruction(int newEnergyPerInstruction)
  {
    int oldEnergyPerInstruction = energyPerInstruction;
    energyPerInstruction = newEnergyPerInstruction;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MCCPackage.CLOUD__ENERGY_PER_INSTRUCTION, oldEnergyPerInstruction, energyPerInstruction));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getEnergyPerMemoryUnit()
  {
    return energyPerMemoryUnit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEnergyPerMemoryUnit(int newEnergyPerMemoryUnit)
  {
    int oldEnergyPerMemoryUnit = energyPerMemoryUnit;
    energyPerMemoryUnit = newEnergyPerMemoryUnit;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MCCPackage.CLOUD__ENERGY_PER_MEMORY_UNIT, oldEnergyPerMemoryUnit, energyPerMemoryUnit));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getEnergyPerDataUnit()
  {
    return energyPerDataUnit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEnergyPerDataUnit(int newEnergyPerDataUnit)
  {
    int oldEnergyPerDataUnit = energyPerDataUnit;
    energyPerDataUnit = newEnergyPerDataUnit;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MCCPackage.CLOUD__ENERGY_PER_DATA_UNIT, oldEnergyPerDataUnit, energyPerDataUnit));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MCCPackage.CLOUD__CPU_INSTRUCTIONS:
        return getCpuInstructions();
      case MCCPackage.CLOUD__ENERGY_PER_INSTRUCTION:
        return getEnergyPerInstruction();
      case MCCPackage.CLOUD__ENERGY_PER_MEMORY_UNIT:
        return getEnergyPerMemoryUnit();
      case MCCPackage.CLOUD__ENERGY_PER_DATA_UNIT:
        return getEnergyPerDataUnit();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MCCPackage.CLOUD__CPU_INSTRUCTIONS:
        setCpuInstructions((Integer)newValue);
        return;
      case MCCPackage.CLOUD__ENERGY_PER_INSTRUCTION:
        setEnergyPerInstruction((Integer)newValue);
        return;
      case MCCPackage.CLOUD__ENERGY_PER_MEMORY_UNIT:
        setEnergyPerMemoryUnit((Integer)newValue);
        return;
      case MCCPackage.CLOUD__ENERGY_PER_DATA_UNIT:
        setEnergyPerDataUnit((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MCCPackage.CLOUD__CPU_INSTRUCTIONS:
        setCpuInstructions(CPU_INSTRUCTIONS_EDEFAULT);
        return;
      case MCCPackage.CLOUD__ENERGY_PER_INSTRUCTION:
        setEnergyPerInstruction(ENERGY_PER_INSTRUCTION_EDEFAULT);
        return;
      case MCCPackage.CLOUD__ENERGY_PER_MEMORY_UNIT:
        setEnergyPerMemoryUnit(ENERGY_PER_MEMORY_UNIT_EDEFAULT);
        return;
      case MCCPackage.CLOUD__ENERGY_PER_DATA_UNIT:
        setEnergyPerDataUnit(ENERGY_PER_DATA_UNIT_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MCCPackage.CLOUD__CPU_INSTRUCTIONS:
        return cpuInstructions != CPU_INSTRUCTIONS_EDEFAULT;
      case MCCPackage.CLOUD__ENERGY_PER_INSTRUCTION:
        return energyPerInstruction != ENERGY_PER_INSTRUCTION_EDEFAULT;
      case MCCPackage.CLOUD__ENERGY_PER_MEMORY_UNIT:
        return energyPerMemoryUnit != ENERGY_PER_MEMORY_UNIT_EDEFAULT;
      case MCCPackage.CLOUD__ENERGY_PER_DATA_UNIT:
        return energyPerDataUnit != ENERGY_PER_DATA_UNIT_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (cpuInstructions: ");
    result.append(cpuInstructions);
    result.append(", energyPerInstruction: ");
    result.append(energyPerInstruction);
    result.append(", energyPerMemoryUnit: ");
    result.append(energyPerMemoryUnit);
    result.append(", energyPerDataUnit: ");
    result.append(energyPerDataUnit);
    result.append(')');
    return result.toString();
  }

} //CloudImpl
