/**
 * generated by Xtext 2.34.0
 */
package org.xtext.mCC.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.mCC.DummyDevice;
import org.xtext.mCC.MCCPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Dummy Device</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DummyDeviceImpl extends DeviceImpl implements DummyDevice
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DummyDeviceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MCCPackage.Literals.DUMMY_DEVICE;
  }

} //DummyDeviceImpl
