/*
 * generated by Xtext 2.34.0
 */
package org.xtext.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.MCCc.ui.internal.MCCcActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MCCExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(MCCcActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		MCCcActivator activator = MCCcActivator.getInstance();
		return activator != null ? activator.getInjector(MCCcActivator.ORG_XTEXT_MCC) : null;
	}

}
